wallpaper {
    monitor = HDMI-A-1
    path = ~/Downloads/vert/
    fit_mode = fill
    timeout = 300
}
wallpaper {
    monitor =
    path = ~/Downloads/walking on water.png
    fit_mode = fill
}
splash = false
